<a href="https://colab.research.google.com/github/Void-Brain70/NumPy/blob/main/NumPy_Array_Shape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Shape of an Array

In [1]:
# Print the shape of a 2-D array
import numpy as np
a = np.array([["Anik","UAP","GSC","DMHS"],["CSE","70","904","4"]])
s = a.shape
print(s)
# returns (2, 4)
# 2 dimensions,each dimension has 4 elements. 

(2, 4)


In [3]:
# Create an array with 5 dimensions
# Using 'ndmin' using a vector with values 1,2,3,4 
# And verify that last dimension has value 4
import numpy as np
a = np.array([1,2,3,4],ndmin=5)
print(a)
print("Array shape:",a.shape)

[[[[[1 2 3 4]]]]]
Array shape: (1, 1, 1, 1, 4)


NumPy Array Reshaping

In [5]:
# Reshaping arrays
# Convert the following 1-D array with 9 elements into a 2-D array.
# The outermost dimension will have 3 arrays, each with 3 elements
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
new_a = a.reshape(3,3)
print(new_a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Reshape From 1-D to 3-D
# Convert the following 1-D array with 8 elements into a 3-D array
# The outermost dimension will have 2 arrays that contains 2 arrays, each with 2 elements
import numpy as np
a = np.array([1,2,3,4,5,6,7,8])
new_a = a.reshape(2,2,2)
print(new_a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
# Check if the returned array is a copy or a view
import numpy as np
a = np.array([1,2,3,4,5,6,7,8])
p = (a.reshape(2,4).base)
print(p)
# The example above returns the original array, so it is a view

[1 2 3 4 5 6 7 8]


In [15]:
# Unknown Dimension
# Pass -1 as the value, and NumPy will calculate this number for you
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
new_a = a.reshape(2, 2, -1)
print(new_a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
# Flattening the arrays
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
new_a = a.reshape(-1)
print(new_a)

[1 2 3 4 5 6]
