<a href="https://colab.research.google.com/github/Void-Brain70/NumPy/blob/main/NumPy_Joining_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Joining NumPy Arrays

In [1]:
# Join two arrays
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([10,20,30])

c = np.concatenate((a1,a2))
print(c)

[ 1  2  3 10 20 30]


In [4]:
# Join two 2-D arrays along rows (axis=1)
import numpy as np
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[10,20],[30,40]])
c = np.concatenate((a1,a2),axis=1)
print(c)

[[ 1  2 10 20]
 [ 3  4 30 40]]


Joining Arrays Using Stack Functions

In [7]:
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([10,20,30])
s = np.stack((a1, a2), axis=1)
print(s)

[[ 1 10]
 [ 2 20]
 [ 3 30]]


In [8]:
# NumPy provides a helper function: hstack() to stack along rows.
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([10,20,30])
s = np.hstack((a1, a2))
print(s)

[ 1  2  3 10 20 30]


In [9]:
# NumPy provides a helper function: vstack()  to stack along columns.
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([10,20,30])
s = np.vstack((a1, a2))
print(s)

[[ 1  2  3]
 [10 20 30]]


In [10]:
# NumPy provides a helper function: dstack() to stack along height, which is the same as depth
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([10,20,30])
s = np.dstack((a1, a2))
print(s)

[[[ 1 10]
  [ 2 20]
  [ 3 30]]]
