<a href="https://colab.research.google.com/github/Void-Brain70/NumPy/blob/main/NumPy_Searching_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Searching Arrays

In [1]:
# Find the indexes where the value is 4
import numpy as np
a = np.array([1,2,3,4,5,4,4])
w = np.where(a==4)
print(w)

(array([3, 5, 6]),)


In [2]:
# Find the indexes where the values are even
import numpy as np
a = np.array([1,2,3,4,5,4,4])
w = np.where(a%2==0)
print(w)

(array([1, 3, 5, 6]),)


In [3]:
# Find the indexes where the values are odd
import numpy as np
a = np.array([1,2,3,4,5,4,4])
w = np.where(a%2==1)
print(w)

(array([0, 2, 4]),)


In [5]:
# Find the indexes where the value 4 should be inserted
import numpy as np
a = np.array([1,2,3,4,5,4,4])
s = np.searchsorted(a,4)
print(s)

3


In [6]:
# Find the indexes where the value 7 should be inserted, starting from the right
import numpy as np
a = np.array([1,2,3,4,5,4,4])
s = np.searchsorted(a,4,side='right')
print(s)

7


In [7]:
# Multiple Values
import numpy as np
a = np.array([1,2,3,4,5,4,4])
s = np.searchsorted(a,[4,4,4])
print(s)

[3 3 3]
