<a href="https://colab.research.google.com/github/Void-Brain70/NumPy/blob/main/NumPy_Sorting_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sorting Arrays

In [1]:
# Sort the array
import numpy as np
a = np.array([3,4,5,1,2,9,8,6,7])
s = np.sort(a)
print(s)

[1 2 3 4 5 6 7 8 9]


In [3]:
# Sort the array alphabetically
import numpy as np
a = np.array(['d','c','e','a','f','b','j','i','h','g'])
s = np.sort(a)
print(s)

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']


In [5]:
# Sort a boolean array
import numpy as np
a = np.array([True, False, True,False])
s = np.sort(a)
print(s)

[False False  True  True]


In [6]:
# If you use the sort() method on a 2-D array, both arrays will be sorted
import numpy as np
a = np.array([[6,5,4],[3,2,1]])
s = np.sort(a)
print(s)

[[4 5 6]
 [1 2 3]]
