<a href="https://colab.research.google.com/github/Void-Brain70/NumPy/blob/main/NumPy_Array_Iterating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Iterating Arrays

In [2]:
# Iterate on the elements of the following 1-D array
import numpy as np
a = np.array([1,2,3,4,5])
for i in a:
  print(i,end=" ")

1 2 3 4 5 

In [4]:
# Iterate on the elements of the following 2-D array
import numpy as np
a = np.array([[1,2,3,4,5],[10,20,30,40,50]])
for i in a:
  print(i)

[1 2 3 4 5]
[10 20 30 40 50]


In [6]:
# Iterate on each scalar element of the 2-D array
import numpy as np
a = np.array([[1,2,3,4,5],[10,20,30,40,50]])
for i in a:
  for j in i:
    print(j,end=" ")

1 2 3 4 5 10 20 30 40 50 

In [9]:
# Iterate on the elements of the following 3-D array
import numpy as np
a = np.array([ [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]] ])

for i in a:
  print("i represents the 2-D array:")
  print(i)

i represents the 2-D array:
[[1 2 3]
 [4 5 6]]
i represents the 2-D array:
[[ 7  8  9]
 [10 11 12]]


In [10]:
# Iterate down to the scalars
import numpy as np
a = np.array([ [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]] ])
for i in a:
  for j in i:
    for k in j:
      print(k,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [11]:
# nditer() is a helping function
# That can be used from very basic to very advanced iterations.
import numpy as np
a = np.array([ [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]] ])

for i in np.nditer(a):
  print(i)


1
2
3
4
5
6
7
8
9
10
11
12


In [12]:
# Iterate through the array as a string
# op_dtypes argument and pass it the expected datatype
# to change the datatype of elements while iterating.
import numpy as np
a = np.array([1,2,3,4,5])
for i in np.nditer(a,flags=['buffered'],op_dtypes=['S']):
  print(i)

b'1'
b'2'
b'3'
b'4'
b'5'


In [13]:
# Iterating With Different Step Size
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for i in np.nditer(a[:,::2]):
  print(i)

1
3
5
7


Enumerated Iteration Using ndenumerate()

Enumeration means mentioning sequence number of somethings one by one.

In [15]:
# Enumerate on following 1D arrays elements
import numpy as np
a = np.array([1,2,3,4,5])
for id, i in np.ndenumerate(a):
  print(id, i)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [16]:
# Enumerate on following 2D array's elements
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for id, i in np.ndenumerate(a):
  print(id, i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
